apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: mro-pulse
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: devops-backend:latest
          imagePullPolicy: Never
          env:
            - name: DB_CONNECTION_STRING
              value: "Host=postgres;Database=postgres;Username=postgres;Password="
            - name: FASTAPI_URL
              value: "http://fastapi:8000"
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: mro-pulse
spec:
  selector:
    app: backend
  ports:
    - port: 8080
      targetPort: 8080