apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mro-pulse-staging
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/mrtoncl/DevOps.git
    targetRevision: devops
    path: mro-pulse-chart
    helm:
      valueFiles:
        - values-staging.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: mro-pulse
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
    - group: apps
      kind: Deployment
      name: backend
      jsonPointers:
        - /spec/replicas